### ISSUE TITLE
Handling pyplot pathological cases

### ISSUE THREAD

**Issue by rmenegaux** [bqplot/bqplot#302] opened 2016-08-24 18:36 UTC
`plt.plot()`  fails with a
`TraitError: Missing scale for data attribute x.`

`plt.plot(y=some_y)` yields the same error, although we do handle `plt.plot(some_y)`

Intuitively, shouldn't `plt.plot()` create a `Lines` with empty `x` and `y`, and shouldn't `plt.plot(y=some_y)` be the same as `plt.plot(some_y)` ?

**Comment by ibdafna** [comment] 2021-01-21 17:53
[2021-01-21] Triage: closing this as bqplot.pyplot does not accept keyword arguments by design.

**Closed by ibdafna** 2021-01-21 17:53 UTC
Labels: Bug
