### ISSUE TITLE
bqplot on python 3.9 in conda-forge?

### ISSUE THREAD

**Issue by JuanCab** [bqplot/bqplot#1246] opened 2020-12-10 14:50 UTC
I normally install packages from conda-forge... noticed bqplot was not available under python 3.9 yet. Is this an issue with the condo-forge feedstock of bqplot or is there a problem with bqplot under python 3.9?

**Comment by ibdafna** [comment] 2020-12-10 17:25
Duplicate of https://github.com/conda-forge/bqplot-feedstock/issues/69.

Closing

**Closed by ibdafna** 2020-12-10 17:25 UTC

**Comment by JuanCab** [comment] 2020-12-14 20:38
I apologize for the duplicate, but both reports should not be closed!

**Comment by JuanCab** [comment] 2020-12-14 20:40
Sorry for the duplicate.
