### ISSUE TITLE
bqplot 0.9 not working with ipywidgets master/notebook master

### ISSUE THREAD

**Issue by mwcraig** [bqplot/bqplot#487] opened 2017-06-19 02:44 UTC
The code below produces the pan/zoom tools, but no plot, with ipywidgets master (which is a few commits past 7.0.0.alpha4). Switching to ipywidgets 6 produces a plot as expected.

The code:
```python
from bqplot import pyplot as plt
import numpy as np

x = np.linspace(0, 4 * np.pi, 100)
y = np.sin(x)
plt.plot(x, y)
plt.show()
```

produces this output:
<img width="619" alt="untitled" src="https://user-images.githubusercontent.com/1147167/27267616-52f267b0-546f-11e7-8251-bf64560972f1.png">

**Comment by dmadeka** [comment] 2017-08-22 02:01
@mwcraig Does everything work now? We always struggle with `ipywidgets` updates

**Comment by mwcraig** [comment] 2017-08-22 02:13
Won't be able to test until Wednesday :(

**Comment by oroszl** [comment] 2017-08-24 21:54
I can confirm that pan/zoom does not work correctly with the most recent ipywidgets. In my case the figure is drawn but activating the pan/zoom button neither pan nor zoom works. downgrading to 6.0.0 resolves the issue.

**Comment by dmadeka** [comment] 2017-08-24 22:18
@oroszl @maartenbreddels fixed it in #530

**Comment by a-fafin** [comment] 2020-07-02 13:45
I have the same problem with bqplots 0.12.13 and ipywidgets 7.5.1. How I can fix it? 
![image](https://user-images.githubusercontent.com/52165481/86366369-017a1a00-bc7b-11ea-96c4-54fa40772bf0.png)

**Comment by SylvainCorlay** [comment] 2020-07-02 14:03
@a-fafin how did you install bqplot?


Also, closing the issue which is super old (2017, bqplot 0.9).

**Closed by SylvainCorlay** 2020-07-02 14:03 UTC

**Comment by a-fafin** [comment] 2020-07-02 14:10
I installed bqplot with pip and I'm on debian.

**Comment by SylvainCorlay** [comment] 2020-07-02 14:11
Do you see any error message in the javascript console? (Ctrl + Shift + J on chrome)

Also, the output of `jupyter nbextension list` may be interesting.

**Comment by a-fafin** [comment] 2020-07-02 14:33
Yes several errors
![image](https://user-images.githubusercontent.com/52165481/86371567-4f921c00-bc81-11ea-8ba7-a629cbf3357a.png)

And the output of `jupyter nbextension list`:
```
Known nbextensions:
  config dir: /home/alexandre/.jupyter/nbconfig
    notebook section
      bqplot/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      bqplot/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      appmode/main  enabled 
      - Validating: OK
      bqplot/extension  enabled 
      - Validating: OK
```

**Comment by SylvainCorlay** [comment] 2020-07-02 14:37
You seem to have bqplot and jupyter widgets enabled in several ways.

Do you have several python environments making use of user-installed packages?

**Comment by martinRenou** [comment] 2020-07-02 14:43
Also the JavaScript is surprising, as it refers to the `BaseModel.js` which was removed in a recent release. So you JS code seems to be out of date (and I guess incompatible with the Python package).

**Comment by SylvainCorlay** [comment] 2020-07-02 14:43
I think that there is an old install of bqplot in a user directory.

**Comment by a-fafin** [comment] 2020-07-02 14:59
Yes maybe I have two python environments, for me and for superuser. Indeed, to execute `jupyter nbextension enable --py --sys-prefix bqplot` I have to be in super-user mode. 

Do you know how I can update my JS code? Except for bqplot, I have no problems with Jupyter or Python. 

I check and I think I have only 1 version of bqplot.

**Comment by a-fafin** [comment] 2020-07-03 09:15
It was that. I had an old version of bqplot in my home directory. Thank you for answering my questions!
