### ISSUE TITLE
Interactive Plot doesn't work under tab widgets

### ISSUE THREAD

**Issue by angang0123** [bqplot/bqplot#1178] opened 2020-07-27 08:11 UTC
Hi, I created a dashboard recently. There is a BrushIntervalSelector in a bqplot Bars object, and this bqplot Bars object is under a widgets.Tab. And it seems that the BrushIntervalSelector doesn't work under the TAB in BQNT... Is this a known issue? Is there any workaround for this? Much appreciate!

**Comment by ChakriCherukuri** [comment] 2020-08-04 16:16
@angang0123 Can you please share the code snippet so we can check it out? Thanks

**Comment by ibdafna** [comment] 2020-08-20 19:45
Dupe of #1180

**Closed by ibdafna** 2020-08-20 19:45 UTC
