### ISSUE TITLE
numpy warning when using plt.plot() in JupyterLab

### ISSUE THREAD

**Issue by ibdafna** [bqplot/bqplot#615] opened 2018-02-19 17:06 UTC
"FutureWarning: Conversion of the second argument of issubdtype from `str` to `str` is deprecated."

Appears to have been introduced in numpy v1.14

This happens when I call plt.plot() in a Jupyter Lab notebook. 

bqplot==0.10.3
ipykernel==4.8.1
ipython==6.2.1
ipywidgets==7.1.2
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterhub==0.8.1
jupyterlab==0.31.8
jupyterlab-launcher==0.10.4
notebook==5.4.0
numpy==1.14.0

**Comment by martinRenou** [comment] 2021-01-26 09:22
I cannot reproduce this warning anymore. I suppose we can close this.

**Closed by martinRenou** 2021-01-26 09:22 UTC
