### ISSUE TITLE
Notebook scrolls when zooming

### ISSUE THREAD

**Issue by Installka** [bqplot/bqplot#1359] opened 2021-06-03 15:02 UTC
**Describe the bug**
Notebook scrolls when using PanZoom after clicking any buttons on Toolbar.

**To Reproduce**
When I run code cell with plot for the first time, everything works fine. But when I click on any button from Toolbar and then click again on PanZoom button, notebook starts scrolling when zooming plot.

You can use this code to reproduce the bug:
```python3
from bqplot import *
from IPython.display import display

x_data = range(10)
y_data = [i ** 2 for i in x_data]

x_sc = LinearScale()
y_sc = LinearScale()

ax_x = Axis(label='Test X', scale=x_sc, tick_format='0.0f')
ax_y = Axis(label='Test Y', scale=y_sc,
            orientation='vertical', tick_format='0.2f')

line = Lines(x=x_data,
             y=y_data,
             scales={'x': x_sc, 'y': y_sc},
             colors=['red', 'yellow'])

fig = Figure(axes=[ax_x, ax_y], marks=[line])

tb = Toolbar(figure=fig)

display(fig)
display(tb)
```

**Expected behavior**
Only plot should scroll when mouse hovers it.

**Additional context**
Bug was reproduced with next setups:
1. Jupyter Lab 3.0.16 running on Windows 7 with bqplot 0.12.27 and Python 3.8.10. I tried to use it with:
Edge 91.0.864.37 (Official build) (64-bit) from Win 7 PC and remotely from Win 10 and macOS 11.4;
Chrome 91.0.4472.77 (Official Build) (64-bit) from Win 7 PC;
Chrome 90.0.4430.0 (Developer Build) (64-bit) remotely from Win 10;
Safari 14.1.1 (16611.2.7.1.4) remotely from macOS 11.4.
2. Jupyter Lab 3.0.10 running on Windows 10 with bqplot 0.12.27 and Python 3.9.5. I tried to use it with Edge 91.0.864.37 (Official build) (64-bit) from Win 10;

I've already seen Pull request https://github.com/bqplot/bqplot/pull/1347, but I don't think it fixed this problem, because I tried to use bqplot 0.12.25, 0.12.26 and 0.12.27.

**Comment by Installka** [comment] 2021-06-03 15:07
I should say, that I'm using bqplot with PanZoom for about a 4 months and everything was OK. But today I've opened my notebook and this problem started to occur. I didn't update any packages, Python or browsers.

**Comment by martinRenou** [comment] 2021-06-03 16:35
Using bqplot with Chromium: 90.0.4430.212 (Official Build) (64-bit) and JupyterLab 3.0.7 I cannot reproduce.

Are you able to reproduce with the Binder? https://mybinder.org/v2/gh/bqplot/bqplot/stable?filepath=examples/Index.ipynb

**Comment by Installka** [comment] 2021-06-03 18:07
@martinRenou In Binder after I click on Toolbar button, zoom stops working at all. Tried Edge 91.0.864.37 (Official build) (64-bit) on Win 10 and macOS 11.4, and Safari 14.1.1 (16611.2.7.1.4). Do this code work perfectly fine in Binder for you?

**Comment by zoccoler** [comment] 2021-06-10 17:17
> I should say, that I'm using bqplot with PanZoom for about a 4 months and everything was OK. But today I've opened my notebook and this problem started to occur. I didn't update any packages, Python or browsers.

I am experiencing this very same problem. The zoom works as long as I don't click any other buttons in a toolbar. After that, it scrolls the notebook screen instead of the graphic no matter which buttons I click.

> Using bqplot with Chromium: 90.0.4430.212 (Official Build) (64-bit) and JupyterLab 3.0.7 I cannot reproduce.
> 
> Are you able to reproduce with the Binder? https://mybinder.org/v2/gh/bqplot/bqplot/stable?filepath=examples/Index.ipynb

I ran the pyplot notebook above and the same thing happens.
I am using bqplot 0.12.17, Chrome version 91.0.4472.101 (Official build) 64 bits and jupyterlab 2.2.6

**Comment by maartenbreddels** [comment] 2021-06-10 17:52
Please update bqplot to 0.12.29, this should be fixed.

**Comment by Installka** [comment] 2021-06-11 13:28
Updated to 0.12.29. Nothing changed.

**Comment by KevoBernardo** [comment] 2021-06-30 22:30
Same here 😥

**Comment by maartenbreddels** [comment] 2021-07-01 06:12
Please provide more information (os, browser+version, bqplot version,
lab/classic)

(from mobile phone)

**Comment by KevoBernardo** [comment] 2021-07-01 13:40
Win10
Microsoft Edge 91.0.864.59  (checked on Google Chrome 91.0.4472.124 too)
Bqplot 0.12.29
Jupyter notebook 6.1.4
Python 3.8.5

**Comment by acelere** [comment] 2021-07-05 13:46
It must be something with Chrome.
Chrome has the "bug" and Firefox does not.
Chrome version: 91.0.4472.124 (Official Build) (64-bit) accessing Jupyterhub serverd notebook with BQPlot 0.12.29
Firefox version: 89.0.2 (64-bit) accessing the same Jupyterhub served notebook

Chrome:
![zoom_bug_chrome](https://user-images.githubusercontent.com/12059585/124480637-79d75780-dd75-11eb-8793-80eba4431c89.gif)


Firefox:
![zoom_bug_firefox](https://user-images.githubusercontent.com/12059585/124480649-7f34a200-dd75-11eb-95cc-c56956744291.gif)

pip freeze on Jupyterhub side:

$ pip freeze
absl-py==0.12.0
aiohttp==3.7.4.post0
alembic==1.6.5
anyio==3.1.0
argon2-cffi==20.1.0
asttokens==2.0.5
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
bleach==3.3.0
bqplot==0.12.29
certifi==2021.5.30
certipy==0.1.3
cffi==1.14.5
chardet==4.0.0
click==8.0.1
colorama==0.4.4
cryptography==3.4.7
cvxpy==1.1.13
cycler==0.10.0
debugpy==1.3.0
decorator==5.0.9
defusedxml==0.7.1
ecos==2.0.7.post1
entrypoints==0.3
executing==0.6.0
flatbuffers==2.0
future==0.18.2
greenlet==1.1.0
h5py==3.2.1
icecream==2.1.1
idna==2.10
ipyfilechooser==0.4.3
ipykernel==5.5.5
ipympl==0.7.0
ipython==7.24.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jax==0.2.14
jaxlib==0.1.67
jedi==0.18.0
jhsingle-native-proxy==0.7.6
Jinja2==3.0.1
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-server==1.8.0
jupyter-telemetry==0.1.0
jupyterhub==1.4.1
jupyterlab==3.0.16
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.0
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
Mako==1.1.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
metakernel==0.27.5
mistune==0.8.4
mpmath==1.2.1
multidict==5.1.0
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
numpy==1.20.3
oauthlib==3.1.1
octave-kernel==0.32.0
opt-einsum==3.3.0
osqp==0.6.2.post0
packaging==20.9
pamela==1.0.0
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
prometheus-client==0.11.0
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.9.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
pytz==2021.1
pyzmq==22.1.0
qdldl==0.1.5.post0
requests==2.25.1
ruamel.yaml==0.17.9
ruamel.yaml.clib==0.2.2
scikit-aero==0.1
scipy==1.6.3
scs==2.1.4
seaborn==0.11.1
Send2Trash==1.5.0
simpervisor==0.4
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.18
sympy==1.8
terminado==0.10.1
testpath==0.5.0
torch==1.8.1+cpu
torchaudio==0.8.1
torchvision==0.9.1+cpu
tornado==6.1
traitlets==5.0.5
traittypes==0.2.1
typing-extensions==3.10.0.0
uncertainties==3.1.5
urllib3==1.26.5
voila==0.2.10
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.1.0
widgetsnbextension==3.5.1
xarray==0.18.2
xeus-python==0.12.4
xlrd==2.0.1
yarl==1.6.3

**Comment by KevoBernardo** [comment] 2021-07-05 14:16
Did you try in Microsoft Edge too? It doesn't work for me

> Win10
> Microsoft Edge 91.0.864.59 (checked on Google Chrome 91.0.4472.124 too)
> Bqplot 0.12.29
> Jupyter notebook 6.1.4
> Python 3.8.5

**Comment by giswqs** [comment] 2021-07-05 18:34
> I have created a fresh new environment with bqplot 0.12.29 and tried to run the "Pyplot.ipynb" under "examples -> Basic Plotting".
> It works only the first time I activate the zoom button. If I deactivate it or click on Reset, and then reactivate it, the zoom stops working (panning still works).
> I am sending attatched the packages' versions from my environment.
> [environment_config.txt](https://github.com/bqplot/bqplot/files/6633816/environment_config.txt)

I can confirm the same issue with bqplot v0.12.29. The zoom button does not work at all with Chrome (Version 91.0.4472.114 64-bit) on Linux. However, it works the first time with the Brave browser (v1.26.74). Once I deactivate it or click on Reset, the zoom button no longer works. I had to restart the Kernel to get it working again. 

![](https://i.imgur.com/3cO58N6.gif)

**Comment by giswqs** [comment] 2021-07-05 18:39
I just tested bqplot v0.12.29 with Microsoft Edge v93.0.910.5 dev 64-bit on Linux. The same issue as I mentioned above. The zoom button only works the first time. 

![](https://i.imgur.com/C3pKs1L.gif)

**Comment by andymcarter** [comment] 2021-07-07 11:47
Experiencing the same as described above, 0.12.29 w/ Chrome no zoom at all but panning fine, w/ Edge zooms once but then not again.

**Comment by Installka** [comment] 2021-07-16 11:18
Updated to 0.12.30. Nothing changed.

**Comment by maartenbreddels** [comment] 2021-08-03 13:51
Related: https://github.com/bqplot/bqplot/issues/1304 and https://github.com/bqplot/bqplot/pull/1347
And this should be fixed in https://github.com/bqplot/bqplot/pull/1391

**Closed** 2021-08-24 08:55 UTC
